### ISSUE TITLE
Is gnss_global compatible with ROS2?

### ISSUE THREAD

**Issue by changh95** [koide3/glim_ext#10]
Hi again,

According to the online documentation, gnss_global is only compatible with ROS2 (https://koide3.github.io/glim/extensions.html).

But then, on the other hand, in the CMakeLists.txt, it says gnss_global does not support ROS2 (https://github.com/koide3/glim_ext/blob/e6d135c0f3d3ddaebc7c31f9f7f19be2e041f37c/CMakeLists.txt#L14).

But then again, in the CMakeLists.txt for gnss_global, it seems like ROS1 and ROS2 builds are both possible.

I'm not sure which one to believe :sweat_smile:

**Comment by koide3** [comment]
Correctly, it now supports only ROS2😅 I migrated from ROS1 to ROS2 while developing this package, and the wrong documentation was left. I'll fix the documentation later.

**Comment by koide3** [comment]
Closing as the doc is fixed with https://github.com/koide3/glim_ext/pull/12
